/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProcuraMelhorEscola.ui.procuraEscola;

import ProcuraMelhorEscola.session.Sessao;
import ProcuraMelhorEscola.ui.ControlaTela;
import ProcuraMelhorEscola.ui.TelasEnum;

/**
 *
 * @author jomar
 */
public class MenuUI extends javax.swing.JPanel {
    private final ControlaTela controlaTela;
    private final Sessao sessao;
    
    
    /**
     * Creates new form MenuUI
     * @param controlaTela
     * @param sessao
     */
    public MenuUI(ControlaTela controlaTela, Sessao sessao) {
        initComponents();
        
        this.controlaTela = controlaTela;
        this.sessao = sessao;
        
        if (!sessao.estaLogado()) {
            controlaTela.mudarTelaPara(
                TelasEnum.LOGIN, 
                "Usuário não está logado ou sessão já expirou"
            );
        }
        
        this.emailLabel.setText(
            this.emailLabel.getText().replace(
                "$EMAIL",
                sessao.pegarDados().pegarEmail()
            )
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        procMelhorEscola = new java.awt.Button();
        estatisticaBtn = new java.awt.Button();
        favoritosBtn = new java.awt.Button();
        label1 = new java.awt.Label();
        emailLabel = new javax.swing.JLabel();
        deslogarBtn = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setText("Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(264, 264, 264))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(37, 37, 37))
        );

        procMelhorEscola.setBackground(new java.awt.Color(242, 242, 242));
        procMelhorEscola.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        procMelhorEscola.setLabel("Procura melhor escola");

        estatisticaBtn.setBackground(new java.awt.Color(242, 242, 242));
        estatisticaBtn.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        estatisticaBtn.setLabel("Estatística");
        estatisticaBtn.setMinimumSize(new java.awt.Dimension(142, 25));
        estatisticaBtn.setPreferredSize(new java.awt.Dimension(142, 25));

        favoritosBtn.setActionCommand("Favoritos");
        favoritosBtn.setBackground(new java.awt.Color(242, 242, 242));
        favoritosBtn.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        favoritosBtn.setLabel("Favoritos");

        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Logado em ");
        label1.setVisible(false);

        emailLabel.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        emailLabel.setText("Logado como $EMAIL");

        deslogarBtn.setBackground(new java.awt.Color(242, 242, 242));
        deslogarBtn.setFont(new java.awt.Font("Liberation Sans", 1, 11)); // NOI18N
        deslogarBtn.setForeground(new java.awt.Color(0, 0, 0));
        deslogarBtn.setText("Deslogar");
        deslogarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deslogarBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(procMelhorEscola, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(estatisticaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(favoritosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deslogarBtn)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(procMelhorEscola, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estatisticaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(favoritosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deslogarBtn))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deslogarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deslogarBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deslogarBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deslogarBtn;
    private javax.swing.JLabel emailLabel;
    private java.awt.Button estatisticaBtn;
    private java.awt.Button favoritosBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Button procMelhorEscola;
    // End of variables declaration//GEN-END:variables
}
